objective:
  - Bilevel Optimization[model=None,n_reg=full,reg=exp,task=datacleaning]
dataset:
  - mnist[ratio=0.5]
solver:
  - MRBO[batch_size=64,eta=0.5,eval_freq=32,n_hia_step=10,outer_ratio=1e-05,step_size=0.31622776601683794]
  - SUSTAIN[batch_size=64,eta=0.5,eval_freq=32,n_hia_step=10,outer_ratio=1e-05,step_size=0.31622776601683794]
  - TTSA[batch_size=64,eval_freq=32,n_hia_step=10,outer_ratio=1e-05,step_size=0.31622776601683794]
  - FSLA[batch_size=64,eval_freq=32,outer_ratio=1e-05,step_size=0.31622776601683794]
  - AmIGO[batch_size=64,eval_freq=32,n_inner_step=10,outer_ratio=1e-05,step_size=0.01]
  - StocBiO[batch_size=64,eval_freq=32,n_inner_step=10,n_shia_steps=10,outer_ratio=0.0001,step_size=0.03162277660168379]
  - BSA[batch_size=64,eval_freq=32,n_hia_step=10,n_inner_step=10,outer_ratio=1e-05,step_size=0.31622776601683794]
  - SABA[batch_size=64,eval_freq=32,outer_ratio=0.0001,step_size=0.1]
  - SOBA[batch_size=64,eval_freq=32,outer_ratio=0.0001,step_size=1.0]
  - SOBA[batch_size=full,eval_freq=4,outer_ratio=1e-05,step_size=1.0]
n-repetitions: 10
max-runs: 64000
timeout: 7200
output: datacleaning0_5_best_params
